### ISSUE TITLE
Cram Issues

### ISSUE THREAD

**Issue by ACEnglish** [lomereiter/sambamba#134]
Is it possible to merge on cram files? I'm currently getting the error:

**sambamba-merge: Error reading BGZF block starting from offset 0: wrong BGZF magic**

Also, I'm seeing an error when trying to use view -f cram:

**[fai_build] fail to write FASTA index original/hg19.fa.fai
Failed to populate reference for id 0
sambamba-view: Failed to write SAM header**

I don't have write permissions in this original/ directory, but original/hg19.fa.fai already exists
Whenever I soft-link orginal/hg19.fa to a directory in which I have write permissions, hg19.fa.fai is created, however I'm still getting the error:

**sambamba-view: Failed to write SAM header**

Finally, What kind of compression parameters can we expect from view -f cram? Is it the lossless compression (-L in cramtools.jar) preserving read names (-n in cramtools.jar) etc, etc?

**Comment by lomereiter** [comment]
Thanks for the report.

* `merge` currently doesn't work with CRAM
* [HTSlib](http://htslib.org) is used for CRAM support (mainly because the format is still changing too quickly to follow its development)
* thus, the compression parameters are the same as with the latest `samtools` (IIRC read names are not preserved, but the sequences and qualities are stored lossless)
* by the same logic, it's a good idea to look at the behaviour of `samtools` and see if it's any different - I guess that the `[fai_build]` issue comes from `htslib`, while the 'failed to write SAM header' is indeed a `sambamba` bug.

**Comment by lomereiter** [comment]
By the way, are the files mapped to the same `original/hg19.fa`? The names in `@SQ` lines of the header must be the same as the names of chromosomes in `hg19.fa`, an error might be because of this. Also please try the latest binary (0.5.4), does it fix the header writing error?

**Comment by ACEnglish** [comment]
Hey! 0.5.4 no longer throws the header writing error. Great work! 
To answer your question, yes - the reference used by sambamba work is the exact same file used for mapping.
