### ISSUE TITLE
In what order are sambamba view parameters processed?

### ISSUE THREAD

**Issue by isthisthat** [lomereiter/sambamba#149]
Hello,
I am doing a sambamba view with sub-sampling, filtering and a region bed file. I was wondering in what order those steps are processed and whether I can control that order.
Thank you.

**Comment by lomereiter** [comment]
Hi,
There is no control over the order, because it's quite reasonable.
First, the BED file is used, because that's the only step where parts of BAM file can be skipped using the index. Next step is subsampling, because random number generation is cheap, whereas a user-provided filter might be costly to apply. Finally the filter is applied.

**Comment by isthisthat** [comment]
Thanks Artem!
