### ISSUE TITLE
Third-party/chanjo integration?

### ISSUE THREAD

**Issue by robinandeer** [lomereiter/sambamba#150]
Hi!

This isn't an issue per se but I'm mainly reaching out to say that I think you've built a very interesting tool :smile: 

#### Background
I've built a tool myself called [chanjo](https://github.com/robinandeer/chanjo) that overlaps quite a bit with what you are doing. Our motivation was a tool that could be used in a clinical setting and BEDTools was too crude.

For this, I'm using Pysam (Samtools) to extract data from the alignment, however, the interface doesn't handle low quality reads/mappings and duplicates in any robust way.

#### Future plans
I think Sambamba already logically discards reads that shouldn't be included, so that's great! I also realized that Sambamba calculates the % coverage above a threshold which is one of the things chanjo does but not BEDTools.

So I have been toying with the idea of just skipping my own solution for doing this and focus chanjo on downstream stuff to make something useful of Sambamba output.

I'll probably be in touch as my plans develop and would love to hear your feedback if you think this is something you are also working on etc.

All-in-all - keep up the great work!

**Comment by lomereiter** [comment]
Hi!

The `depth` tool was also created for clinical sequencing purposes, and at the time (a year ago) the alternatives were either `BEDtools` or various clunky and slow home-made Python scripts. Now I see that the times have changed :) I appreciated the documentation and codebase of `chanjo` and I must say it's all high quality. So keep up the great work too!

Regarding your future plans, I think the integration of `depth` tool output should be fairly easy, it seems that it's not much different from `chanjo annotate`. I would be happy to see that too, because I left the preparation of input BED and post-processing the results to other bioinformaticians, and your tool appears to do just that in a convenient fashion.

**Comment by robinandeer** [comment]
Awesome - and thank you!

Then I will go ahead with my plans then

The Sambamba output really is very straight forward to parse, the only thing would be to add a header so that you can easily parse the threshold levels used when running ``depth`` but I guess that is in the works already which is great

**Comment by lomereiter** [comment]
I added the headers to the output (#145), the corresponding columns are named `percentage<threshold level>`, e.g. `percentage30`
