### ISSUE TITLE
Chunking BAM files in low variation regions

### ISSUE THREAD

**Issue by pjotrp** [lomereiter/sambamba#158]
For WGS parallel processing it can be useful to work with smaller chunks of BAM files which are merged in a final step. 

Chunking can already be done at the chromosome level, but this leaves much to be desired for in terms of processing speed. Finer chunking would allow for splitting work over 1000 cores, for example
and (for one) save variant callers to implement their own chunking mechanisms.

Splitting could be done in regions of low variation or missing data. Parameters would be minimum chunk length (say a default of 1 million BP), low variation window size (say 300 BP). Output are BAM files which could be named with chr, start-end pos and a serial number.

**Comment by lomereiter** [comment]
Perhaps Brad (@chapmanb) could add to your suggestion? As far as I understand, bcbio-nextgen [does almost the same](https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/bam/callable.py), but splits files on regions with no coverage instead of low variation. I have no idea how well that performs in practice, but mathematical considerations suggest that with splitting on zero-covered bases reasonable degree of parallelism is obtained only for coverage ≤ 15. (at 20 the expected number of gaps is already almost zero: exp(-20) * 10**8 = 0.2, assuming Poisson distribution and 100Mb chr)

**Comment by chapmanb** [comment]
Artem;
Pjotr brought up this idea after we discussed having a stand alone approach that would do this. I'd happily migrate off our custom code in bcbio to something more general if it were available. 

The no-coverage approach works okay since the distribution of coverage is non-random and influenced by poorly represented regions. However, enhancing it with no-variation regions would be a big help since it could let us have a more uniform distribution of pieces. This is definitely something I'd like to have.

So, happy to help with anything I could and provide testing/suggestions if you have interest in working on this. Thanks much.

**Comment by lomereiter** [comment]
Brad,
I will definitely look into this at some point. Just found out that your current approach is criticized in the [Churchill paper](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4333267/) as non-uniform. (I won't even download it to avoid infringing their ridiculous patent; and yes, I saw [this thread](https://www.biostars.org/p/129293/) on BioStars.)

**Comment by chapmanb** [comment]
Artem;
The bcbio approach is definitely non-optimal in terms of uniformity, so there is lots of room for improvement. I'd characterize the approach in bcbio as conservative, easy to implement and good enough for most cases. Adding in splitting in non-variable regions as Pjotr suggested is a good step forward and should get much more uniform splitting. Thanks again for thinking about this.

**Comment by inijman** [comment]
We used this approach before and we chose to split on the 'N' regions in the genome, where you have no data regardless of the coverage / variation. And the split regions are stable and comparable between samples as long as the reference does not change. Only issue is the pairs mapping over the N-stretch as they will be broken up, but for the rest it is the safest route.

**Comment by pjotrp** [comment]
Inactive
