### ISSUE TITLE
Allow sort to directly read SAM format

### ISSUE THREAD

**Issue by schelhorn** [lomereiter/sambamba#165]
It would be very nice if `sort` could directly read SAM format, without requiring piping from `view` to do SAM to BAM conversion. Somehow it is wasteful to parse and pack SAM into BAM in `view`, just for `sort` to parse the whole thing again for sorting. I suggest that the `view` command syntax for specifying input formats could directly be added to `sort`.

**Comment by lomereiter** [comment]
I assure you that once you specify `-l 0` (`--compression-level=0`) in the `view` command, the overhead will be minimal ;)
To be frank, I have very little incentive to add SAM support for anything other than `view`, because text parsing is much slower than reading binary data. Thus, the only use case I support is reading aligners' output.

**Comment by schelhorn** [comment]
I see, thanks!
