### ISSUE TITLE
sambamba depth region count reads wrongly

### ISSUE THREAD

**Issue by kongdeju** [lomereiter/sambamba#198]
version v0.5.9

sambamba depth region -L hg19.test.bed WGC062727U.sort.bam

the out is inconsistance with samtools view count or sambamba view count

**Comment by lomereiter** [comment]
Hi,
The differences are because `depth region` by default filters out reads of bad quality (see also #191). In fact, the flags are meant to match `bedtools multicov` (https://github.com/lomereiter/sambamba/commit/609ab310d966b422fd913e4612072b470245eafc).

But that's not the whole story (as recent testing revealed): consider a region that happens to be completely inside a deletion; `view` cares only about overlaps and thus counts the read, while `depth` doesn't consider the region being covered by the read.
