### ISSUE TITLE
sambamba with denovogear

### ISSUE THREAD

**Issue by gpcr** [lomereiter/sambamba#207]
how to use sambamba mpileup along with Denovogear on the fly?

similar to "samtools mpileup -gDf hg19.fa s1.bam s2.bam s3.bam | ./denovogear dnm auto --ped t.ped --bcf -"

thanks

**Comment by lomereiter** [comment]
Hi, short answer is: it's currently either impossible or just doesn't make sense.
However, I'll look into that because it was part of the original idea to support other callers.

Long story: pileup by itself is not that computationally expensive, calling is. Parallelizing variant calling by chromosome is sub-optimal and not always feasible. `sambamba mpileup` introduces more fine-grained approach, but it has to be taught first about the caller command-line arguments, currently it's done only for bcftools as the most natural target.
