### ISSUE TITLE
Trouble compiling on PowerPC 64-bit

### ISSUE THREAD

**Issue by IvantheDugtrio** [lomereiter/sambamba#233]
I get the following error when trying to compile with LDC 0.17.1, Clang 3.5.0, and Debian 8.5 powerpc64 big-endian. 

The make ends with 
"/usr/bin/ld: build/sambamba.o: file class ELFCLASS64 incompatible with ELFCLASS32"
"/usr/bin/ld: final link failed: File in wrong format"

[sambamba-error.txt](https://github.com/lomereiter/sambamba/files/355441/sambamba-error.txt)

**Comment by IvantheDugtrio** [comment]
Building from the LLVM 3.7 release followed by building LDC 0.17 seems to have resolved this issue.

**Comment by lomereiter** [comment]
Congratulations!
Now you should run the tests, because you seem to be the first big-endian user:
1) `cd` to `BioD` folder and run `rdmd -unittest -d test/unittests.d`
2) Go back to the project root, download and unpack [shunit2](http://sourceforge.net/projects/shunit2/files/shunit2%202.0.X%20%28stable%29/2.0.3/) and run `sh .test_suite.sh`
3) Put any failures into a new issue
