### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ernfrid** [lomereiter/sambamba#243]
Hi,

We're currently trying to button down a pipeline and were wondering if you might consider releasing a new version so that there is a stable version containing https://github.com/biod/BioD/pull/21 that we could utilize.

Thanks for your consideration!

**Comment by lomereiter** [comment]
Hi,

I can add a git tag, but I'm reluctant to produce a new binary release.

Here's the situation in full:
* so far I've been building packages for CentOS 6 so that they work for everyone
* however, CentOS 6 [doesn't play well](http://lists.llvm.org/pipermail/llvm-dev/2016-June/101670.html) with latest LLVM releases (3.5+), or maybe the other way around
* binaries built inside the CentOS 6 docker container appear to segfault more often than what's built with latest LLVM versions (needs to be checked by more people)
* the above leads to suspect some bugs in LLVM 3.4, see also https://github.com/ldc-developers/ldc/issues/1038
* besides, LDC developers [agreed](http://forum.dlang.org/thread/drvgvolvrppushpqfjlp@forum.dlang.org) to drop support for LLVM 3.4 more than one year ago, so that newer LDC releases are untested against it (starting from 0.17 as far as I can tell)
* just in case, GDC is not an option since it has less development resources than LDC and so even more bugs, and DMD is not an option because its optimization facilities are plain terrible

CentOS 6 is not dead yet, it's going to be kicking until [end of 2020](https://wiki.centos.org/FAQ/General#head-fe8a0be91ee3e7dea812e8694491e1dde5b75e6d).  New LLVM versions need glibc 2.14 at least, and I had a ticket regarding non-working LDC build just a couple of months ago (https://github.com/lomereiter/sambamba/issues/231). 

@pjotrp any thoughts? Could `guix` be used to help in fighting this insanity?

See also https://github.com/Linuxbrew/homebrew-science/issues/257 where bottles were built for CentOS 7 with quite a bit of jumping through hoops (kudos to everyone involved, I'm very impressed by this effort).

**Comment by ernfrid** [comment]
Well that all sounds horrible. 😢 

I believe we were able to get a local compilation (on Ubuntu 10.04) with some hoop jumping as well so a git tag would certainly be enough for my (admittedly selfish) needs.

**Comment by pjotrp** [comment]
GNU Guix would solve the deployment issues with ldc/LLVM in a distribution agnostic way and would be a sane way forward from a development perspective. I am willing to work on that a bit later this year. It would be a good way forward because we will also add Conda support from Guix and (hopefully) get non-root installs.

**Comment by ernfrid** [comment]
I just wanted to follow up and ask about this again. Do you think you will be releasing a new git tag soon? Thanks again!

**Comment by lomereiter** [comment]
Good news: I've managed to find a CentOS 6 Docker image with LLVM 3.8 and compiled LDC 0.17.1 on it (which should allow to compile latest LDC but I didn't go into that). So the new release is finally out there.

**Comment by ernfrid** [comment]
Hurray! Thank you so much!

**Comment by sambrightman** [comment]
Great news. Is there any reason to stick with LDC 0.17.1 instead of 1.0.0? Maybe due to bootstrapping? Maybe pre-built 0.17.1 be used to build 1.0.0/1.1.0.

Relatedly, I think debugging (either locals or unmangling or both) is broken in several combinations, but LDC 1.1 should fix for LLVM 3.8+. I had it working on LLVM 3.7.1 + LDC 1.0.0.
